import type { CashflowHealthScore, Transaction } from '../types';
import { formatCurrency, getMonthName } from '../lib/utils';

interface ReportPdfInput {
  month: number;
  year: number;
  transactions: Transaction[];
  healthScore?: CashflowHealthScore;
}

export function exportMonthlyReportPdf(input: ReportPdfInput) {
  const monthlyTransactions = input.transactions.filter((transaction) => {
    const date = new Date(transaction.date);
    return date.getMonth() + 1 === input.month && date.getFullYear() === input.year;
  });
  const income = monthlyTransactions
    .filter((transaction) => transaction.type === 'income' || transaction.type === 'refund')
    .reduce((sum, transaction) => sum + transaction.amount, 0);
  const expense = monthlyTransactions
    .filter((transaction) => transaction.type === 'expense' || transaction.type === 'transfer')
    .reduce((sum, transaction) => sum + transaction.amount, 0);
  const rows = monthlyTransactions
    .slice(0, 80)
    .map((transaction) => `
      <tr>
        <td>${escapeHtml(transaction.date)}</td>
        <td>${escapeHtml(transaction.merchant || '-')}</td>
        <td>${escapeHtml(transaction.categoryName)}</td>
        <td>${escapeHtml(transaction.type)}</td>
        <td class="amount">${formatCurrency(transaction.amount)}</td>
      </tr>
    `)
    .join('');

  const html = `
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>CashFlow Report ${getMonthName(input.month)} ${input.year}</title>
        <style>
          @page { margin: 18mm; }
          * { box-sizing: border-box; }
          body {
            margin: 0;
            font-family: Manrope, Inter, Arial, sans-serif;
            color: #111827;
            background: #ffffff;
          }
          .header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 18px;
            margin-bottom: 22px;
          }
          .brand { font-size: 12px; color: #6b7280; letter-spacing: .16em; text-transform: uppercase; }
          h1 { margin: 6px 0 0; font-size: 28px; }
          .score {
            text-align: right;
            padding: 12px 14px;
            border-radius: 14px;
            background: #f5f3ff;
            color: #5b21b6;
          }
          .score strong { display: block; font-size: 28px; }
          .grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 12px;
            margin-bottom: 24px;
          }
          .card {
            border: 1px solid #e5e7eb;
            border-radius: 16px;
            padding: 14px;
            background: #fafafa;
          }
          .label { font-size: 11px; color: #6b7280; margin-bottom: 6px; }
          .value { font-size: 18px; font-weight: 800; }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 11px;
          }
          th {
            text-align: left;
            color: #6b7280;
            border-bottom: 1px solid #e5e7eb;
            padding: 9px 6px;
          }
          td {
            border-bottom: 1px solid #f3f4f6;
            padding: 9px 6px;
          }
          .amount { text-align: right; font-weight: 700; }
          .footer {
            margin-top: 18px;
            color: #6b7280;
            font-size: 10px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="brand">CashFlow Professional Report</div>
            <h1>${getMonthName(input.month)} ${input.year}</h1>
          </div>
          ${input.healthScore ? `<div class="score"><span>Health Score</span><strong>${input.healthScore.score}</strong></div>` : ''}
        </div>
        <div class="grid">
          <div class="card"><div class="label">Pemasukan</div><div class="value">${formatCurrency(income)}</div></div>
          <div class="card"><div class="label">Pengeluaran</div><div class="value">${formatCurrency(expense)}</div></div>
          <div class="card"><div class="label">Net Cashflow</div><div class="value">${formatCurrency(income - expense)}</div></div>
        </div>
        <table>
          <thead>
            <tr><th>Tanggal</th><th>Merchant</th><th>Kategori</th><th>Tipe</th><th class="amount">Nominal</th></tr>
          </thead>
          <tbody>${rows || '<tr><td colspan="5">Belum ada transaksi bulan ini.</td></tr>'}</tbody>
        </table>
        <div class="footer">Generated by CashFlow. Gunakan dialog print browser untuk Save as PDF.</div>
        <script>window.onload = () => window.print();</script>
      </body>
    </html>
  `;

  const printWindow = window.open('', '_blank', 'width=960,height=720');
  if (!printWindow) throw new Error('Popup diblokir browser. Izinkan popup untuk export PDF.');
  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
